### ISSUE TITLE
The deploy script is missing the amending of the unoconv script to set the python location

### ISSUE THREAD

**Issue by fgregg** [datamade/metro-pdf-merger#16]
This causes the conversions to fail, because unoconv would fail.

Really, we should probably take the unconv bits out of the deploy script altogether as we don't have great control over  https://raw.githubusercontent.com/dagwieers/unoconv/master/unoconv

**Comment by fgregg** [comment]
The last deploy looks to have happened in September 2017, but it seems unlikely that if that is so we are only seeing this problem now.

**Comment by reginafcompton** [comment]
I actually do not remember using Codedeploy to deploy this app, though it looks like we have scripts - from the generous hand of Eric - to do it, and the AWS console said it happened in September.

I suspect that in September I fixed an unoconv problem on the server, but without altering the deploy scripts. (That's obviously not a very good thing to do.) I'd be curious to know why unoconv failed tonight, however - the merger has been merging packets and finding unoconv for some time. 

I'll look at this issue on Monday.

**Comment by reginafcompton** [comment]
Added: `#!/usr/bin/python3` to the top of `/home/datamade/unoconv/unoconv`

Then, ran: `python manage.py compile_pdfs --all_documents`

We should remove the following from `after_install` - since it seems unsafe to constantly update these dependencies:

```
apt-get update
apt-get -y install libreoffice-script-provider-python
apt-get -y install libreoffice-writer
apt-get -y install libreoffice-calc
apt-get -y install libreoffice-impress

mkdir -p /home/datamade/unoconv
wget -O /home/datamade/unoconv/unoconv https://raw.githubusercontent.com/dagwieers/unoconv/master/unoconv
# Make a symbolic link
ln -s -f /home/datamade/unoconv/unoconv /usr/bin/unoconv
chmod a+x /home/datamade/unoconv/unoconv
```

**Comment by reginafcompton** [comment]
**Second thoughts**

The amendment of the correct Python path did not fix the issue. 
* the error persists in the log `/tmp/metro-pdf-worker-d-XSTH3EHWO-err.log`, even after we made the change to the unoconv file. Here's the error:
```
unoconv: Cannot find a suitable pyuno library and python binary combination in /usr/lib/libreoffice
ERROR: No module named uno
```
* An actual example demonstrates the issue - [this board report packet](https://boardagendas.metro.net/board-report/2016-0062/) does not have Attachment A and C, which are word doc files.

So, unoconv continues to fail, even with the correct python location. We need to determine why.

**Comment by reginafcompton** [comment]
I have an answer re: the original issue. The sql query that helps build the event packets only looks at new bills: https://github.com/datamade/la-metro-councilmatic/blob/master/lametro/management/commands/compile_pdfs.py#L187

That's a problem, since Metro can add an EventDocument, but not a related BillDocument. (N.B. Fortunately, it seems like that's not a frequent occurrence, considering that this issue did not arise earlier.) 

I will make a change to the SQL query to look for instances of a `new_eventdocument` in addition to `new_billdocument`.

**Comment by reginafcompton** [comment]
**Pull Requests**

(1) This PR solves the reported problem, i.e., the March 22 Board Meeting did not have an agenda packet: https://github.com/datamade/la-metro-councilmatic/pull/279

(2) This PR solves the problem stated at the top of this issue, i.e., the deploy scripts did not amend the python location to the `unoconv` file, causing the conversion of non-pdf attachments to fail: https://github.com/datamade/metro-pdf-merger/pull/18

@fgregg, I requested your review on both.

**Comment by reginafcompton** [comment]
Closed via https://github.com/datamade/la-metro-councilmatic/pull/279 and PR #18
